// SPDX-FileCopyrightText: 2017 ~ 2022 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

// This file was generated by dtk-settings-tools version 0.1.2 

#include <DSettings>

void GenerateSettingTranslate()
{
    auto custom_screensaver_slideshow_shuffleText = QObject::tr("Shuffle");
    auto custom_screensaver_slideshow_time_intervalName = QObject::tr("Time interval");
    auto custom_screensaver_slideshow_time_intervalText0 = QObject::tr("1 minutes");
    auto custom_screensaver_slideshow_time_intervalText1 = QObject::tr("3 minutes");
    auto custom_screensaver_slideshow_time_intervalText2 = QObject::tr("5 minutes");
    auto custom_screensaver_slideshow_time_intervalText3 = QObject::tr("10 minutes");
    auto custom_screensaver_slideshow_time_intervalText4 = QObject::tr("30 minutes");
    auto custom_screensaver_slideshow_time_intervalText5 = QObject::tr("60 minutes");
    auto group_custom_screensaverName = QObject::tr("Custom Screensaver");
    auto group_custom_screensaver_pathName = QObject::tr("Path");
    auto group_custom_screensaver_slideshowName = QObject::tr("Slideshow");
}
